### ISSUE TITLE
License

### ISSUE THREAD

**Issue by labrax** [yandexdataschool/roc_comparison#4]
Dear yandexdataschool, 

Thanks for sharing these scripts with us. They are very easy and useful!

Could you add a license for the files you have in this repository?

Kind regards,
Victor

**Comment by timfei1101** [comment]
Dear yandexdataschool,

Yeah I agree with labrax, indeed the code is really useful. I'd love to know if any license is available for us? Thanks!

**Comment by kazeevn** [comment]
Thank you for dropping by! Looks like I need to review my GitHub notification settings.
