### ISSUE TITLE
Compare mean AUC to a constant predictor

### ISSUE THREAD

**Issue by annukkaa** [yandexdataschool/roc_comparison#7]
Hello,
I was reading the paper "A rapid volume of interest-based approach of radiomics analysis of breast MRI for tumor decoding and phenotyping of breast cancer" by Demircioglu et al. 2020, where the authors employ the DeLong test to compare if the AUC of ROC curves is different to that of a constant predictor, with the code is this repo.

In this paper the authors compute the **average** AUC's over the test sets of 25 repeats of 5-fold cross-validation.

I have a similar situation. I have an average AUC (over 100 different, but not independent test sets) and would like to see if this average is significantly different to that of a constant predictor.

How can I use this code to perform this analysis? I can't figure this out from the example script.

Thank you!

**Comment by kazeevn** [comment]
Hello,

Firstly, on the matter of comparing to a constant predictor. For the DeLong method it doesn't matter how you obtain your predictions, and it should work with the constant ones as well.

Secondly, about the different, but not independent test sets. Unfortunately, the code here does only two things:
1. Computing variance of an AUC estimate over a test set
2. Computing p-value of the hypothesis that two models have the same expected true value of AUC, given the predictions of the models on the same test dataset.

100 different, but not independent test sets looks like a tricky case to rigorously analyze, as a lot depends on how exactly they are dependent.
